import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI to teachers",
  description: "Generated by Felipe Domingues",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body className={inter.className}>
        {children}
        {modal}
        <div id="modal-root" />
      </body>
    </html>
  );
}
